### ISSUE TITLE
Suggestion for the docs - for when using authentication

### ISSUE THREAD

**Issue by codewise-nicolas** [ryancco/laravel-pages#7]
I like your package because it will allow me to quickly build out static pages that are styled within the rest of the applications look and feel, without having to setup routes and controllers for them.
I came across a problem with authentication and this is what I had to do, possibly you can add it to the readme for others.

1. As part of installation, users dont forget to run the vendor:publish artisan command to make the config/pages.php config file because of #2 below.
2. If people use authentication or such, any @auth or similar blade commands wont function by default due to the default middleware being set in the pages.php config file; it will actually loose the session cookies and log the user out. Therefore set the middleware setting to 'web' and it will use the same middleware as the rest of the web app.
`'middleware' => 'web'`

Thanks again for the great little package.

**Comment by ryancco** [comment]
Thanks for the feedback! I will absolutely add this to the docs, and probably rewrite them in general. Glad you’re using it, and I appreciate any other feedback.

**Comment by ryancco** [comment]
Updated :)
